SymfonyContrib\Bundle\TaxonomyBundle\Entity\TermMap:
    type: entity
    table: taxonomy_term_map
    manyToOne:
        term:
            targetEntity: Term
            inversedBy: map
            fetch: EAGER
            joinColumn:
                name: tid
                referencedColumnName: id
                onDelete: CASCADE
    uniqueConstraints:
        taxonomy_term_map_unique:
            columns:
                - tid
                - owner
                - oid
    indexes:
        taxonomy_term_map_tid:
            columns:
                - tid
        taxonomy_term_map_oid:
            columns:
                - oid
        taxonomy_term_map_field:
            columns:
                - field
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        termId:
            column: tid
            type: integer
            options:
                comment: Term ID
        owner:
            type: string
            length: 255
            options:
                comment: Name of the referencing object.
        ownerId:
            column: oid
            type: integer
            options:
                comment: ID of the referencing object.
        field:
            type: string
            length: 255
            options:
                comment: Field/property of referencing object.
        createdAt:
            type: datetime
            options:
                comment: Date and time this mapping was created.
