services:
    taxonomy:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Taxonomy
        arguments:
            - "@doctrine.orm.entity_manager"

    taxonomy.doctrine.event_subscriber:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Doctrine\EventSubscriber
        tags:
            - name: doctrine.event_subscriber

    taxonomy.form.vocabulary:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\VocabularyForm
        tags:
            - name: form.type

    taxonomy.form.term:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\TermForm
        tags:
            - name: form.type

    taxonomy.form.type.taxonomy_text:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TaxonomyTextType
        arguments:
            - "@taxonomy"
        tags:
            - name: form.type

    taxonomy.form.type.taxonomy_choice:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TaxonomyChoiceType
        arguments:
            - "@taxonomy"
        tags:
            - name: form.type

    taxonomy.form.terms_sort:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\TermsSortForm
        tags:
            - name: form.type

    taxonomy.form.type.term_entity:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TermEntityType
        arguments:
            - "@taxonomy"
        tags:
            - name: form.type
