services:
    taxonomy:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Taxonomy
        arguments:
            - "@doctrine.orm.entity_manager"

    taxonomy.repository.term:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Entity\Repository\TermRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - SymfonyContrib\Bundle\TaxonomyBundle\Entity\Term

    taxonomy.form.vocabulary:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\VocabularyForm
        tags:
            - name: form.type

    taxonomy.form.term:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\TermForm
        tags:
            - name: form.type

#    taxonomy.form.type.taxonomy_text:
#        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TaxonomyTextType
#        arguments:
#            - "@taxonomy.repository.term"
#        tags:
#            - name: form.type
#
#    taxonomy.form.type.taxonomy_choice:
#        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TaxonomyChoiceType
#        arguments:
#            - "@taxonomy.repository.term"
#        tags:
#            - name: form.type

    taxonomy.form.terms_sort:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\TermsSortForm
        tags:
            - name: form.type

    taxonomy.form.type.term_entity:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TermEntityType
        arguments:
            - "@taxonomy.repository.term"
        tags:
            - name: form.type

    taxonomy.form.type.tag:
        class: SymfonyContrib\Bundle\TaxonomyBundle\Form\Type\TagType
        arguments:
            - "@taxonomy.repository.term"
        tags:
            - name: form.type
