SymfonyContrib\Bundle\TaxonomyBundle\Entity\Vocabulary:
    properties:
        label:
            - NotBlank: ~
        name:
            - NotBlank: ~
        desc:
            - NotNull: ~
        weight:
            - Type:
                type: integer
        createdAt:
            - DateTime: ~


SymfonyContrib\Bundle\TaxonomyBundle\Entity\Term:
    properties:
        name:
            - NotBlank: ~
        desc:
            - NotNull: ~
        weight:
            - Type:
                type: integer
        createdAt:
            - DateTime: ~
#        vocabulary:
#            - Valid: ~
