SymfonyContrib\Bundle\TaxonomyBundle\Entity\Vocabulary:
    properties:
        label:
            - NotBlank: ~
        name:
            - NotBlank: ~
        desc:
            - NotNull: ~
        weight:
            - Type:
                type: integer
        created:
            - DateTime: ~


SymfonyContrib\Bundle\TaxonomyBundle\Entity\Term:
    properties:
        name:
            - NotBlank: ~
        desc:
            - NotNull: ~
        weight:
            - Type:
                type: integer
        created:
            - DateTime: ~
#        vocabulary:
#            - Valid: ~

SymfonyContrib\Bundle\TaxonomyBundle\Entity\TermMap:
    properties:
        term:
            - Valid: ~
        owner:
            - NotBlank: ~
            - Type:
                type: string
        ownerId:
            - NotBlank: ~
            - Type:
                type: string
        created:
            - DateTime: ~
